### ISSUE TITLE
macOS: Build Fails, Seeed_Arduino_FreeRTOS.h Not Found

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Seeed_Arduino_edgeimpulse#2]
I've followed the procedure but `./arduino-build.sh --build` fails with the following error:

```
% cd /Users/USER/Arduino/Libraries/Seeed_Arduino_edgeimpulse
% ./arduino-build.sh --build

Building Seeed_Arduino_edgeimpulse.ino
Still building...
In file included from /Users/USER/Arduino/Libraries/Seeed_Arduino_edgeimpulse/Seeed_Arduino_edgeimpulse.ino:24:0:
/var/folders/wn/n7qqb8ss0k3bvpqwfcdwp_7r0000gn/T/arduino-sketch-5058F1AF8388633F609CADB75A75DC9D/sketch/src/setup.h:25:10: fatal error: Seeed_Arduino_FreeRTOS.h: No such file or directory
 #include "Seeed_Arduino_FreeRTOS.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Error during build: exit status 1
./arduino-build.sh: line 44: exit: Building Seeed_Arduino_edgeimpulse.ino failed: numeric argument required
```

The `Seeed_Arduino_FreeRTOS.h` header file is located at `/Users/USER/Arduino/Libraries/Seeed_Arduino_FreeRTOS/src/Seeed_Arduino_FreeRTOS.h`.

What's going on?

```
% uname -a
Darwin MacBook.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
% arduino-cli version
arduino-cli Version: 0.11.0 Commit: 0296f4df116385f868b67c5ffa7393936c3345c9
``

**Comment by Pillar1989** [comment]
Refer to CI for specific compilation method
https://github.com/Seeed-Studio/Seeed_Arduino_edgeimpulse/blob/master/.travis.yml

**Comment by rei-vilo** [comment]
I can’t see any difference between the CI and the [Building the application](https://github.com/Seeed-Studio/Seeed_Arduino_edgeimpulse#building-the-application) I’ve followed with the error mentioned earlier. 

Would you mind using the standard Arduino IDE instead of Arduino-CLI to build the example? 

Thank you!

**Comment by Pillar1989** [comment]
The main reason is that the SDK of EdgeImpulse does not conform to the directory structure of the Arduino Library.We need to follow the rules of the upstream game. @rei-vilo

**Comment by rei-vilo** [comment]
Thank you for the explanation. Still no luck in building it. 

Would it be possible to provide the executable, either as a `.bin` or `.uf2` file? 

Thank you!

**Comment by Pillar1989** [comment]
There you go , It's mentioned in the wiki.
https://wiki.seeedstudio.com/Wio-Terminal-Edge-Impulse/#1-connect-the-development-board-to-your-computer

**Comment by rei-vilo** [comment]
Thank you, it will easier that way.
