### ISSUE TITLE
wio-terminal-ei-1.4.0.uf2 timeout issue

### ISSUE THREAD

**Issue by aprokid** [Seeed-Studio/Seeed_Arduino_edgeimpulse#5]
Hi, I used wio-terminal-ei-1.4.0.uf2 for uploading my accelerometer data on edge impulse. The first few samples uploaded successfully, but it showed timeout error afterwards. I'm not sure what is the problem is.

https://github.com/Seeed-Studio/Seeed_Arduino_edgeimpulse/releases/tag/1.4.0

![image](https://user-images.githubusercontent.com/67274126/149463880-7488fc5e-53de-4113-840d-9c376aed277f.png)

**Comment by Pillar1989** [comment]
@0hotpotman0  any idea ?
